""" "add_user_phone"

Revision ID: 721e91193dc8
Revises: 9b67dfe8b6fb
Create Date: 2025-07-31 15:11:02.665775

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "721e91193dc8"
down_revision = "9b67dfe8b6fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_memberships_user_id"), table_name="memberships")
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_unique_constraint(None, "memberships", ["id"])
    op.drop_index(op.f("idx_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("idx_organizations_status"), table_name="organizations")
    op.create_index(op.f("ix_organizations_status"), "organizations", ["status"], unique=False)
    op.create_unique_constraint(None, "organizations", ["id"])
    op.add_column("users", sa.Column("phone", sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone")
    op.drop_constraint(None, "organizations", type_="unique")
    op.drop_index(op.f("ix_organizations_status"), table_name="organizations")
    op.create_index(op.f("idx_organizations_status"), "organizations", ["status"], unique=False)
    op.create_index(op.f("idx_organizations_slug"), "organizations", ["slug"], unique=False)
    op.drop_constraint(None, "memberships", type_="unique")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.create_index(op.f("idx_memberships_user_id"), "memberships", ["user_id"], unique=False)
    # ### end Alembic commands ###
