name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # weekly Monday 03:00 UTC

jobs:
  bandit-and-safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-interaction --with linters,tests --no-root

      - name: Bandit
        run: poetry run bandit -r . -c pyproject.toml

      - name: Safety
        run: poetry run safety check --full-report
